spring:
  application:
  name: fleet management API

  datasource:
    url: jdbc:postgresql://db-fleet-management.postgres.database.azure.com:5432/postgres?user=${DB_USER}&password=${DB_PASSWORD}&sslmode=require
    jpa:
      hibernate:
        ddl-auto: create
        naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  servlet:
    context-path: /fleet-management-api